### ISSUE TITLE
Promise support + existsSymlinks

### ISSUE THREAD

**Issue by zkochan** [Kikobeats/exists-file#4]
Hi, I need a package like this in [pnpm](https://github.com/rstacruz/pnpm).

Would you accept a pull request that would add promise to the async function and maybe a new existsSymlink function?

**Comment by Kikobeats** [comment]
absolutely!

If `cb` is provided in the async method use it; otherwise, return a promise. I used that in other projects.

Example: https://github.com/Kikobeats/json-future/blob/master/lib/index.js#L39-L40

**Comment by Kikobeats** [comment]
Also take in consideration the node environment. I prefer don't include a promise polyfill, so I accept drop [old node versions](https://github.com/Kikobeats/exists-file/blob/master/.travis.yml#L7-L8).

**Comment by zkochan** [comment]
I also have a nice plugin for testing usage examples in Readme. It would be nice to test the example in this package. https://github.com/mosjs/mos/tree/master/packages/mos-plugin-example

**Comment by zkochan** [comment]
I think this validation check is weird https://github.com/Kikobeats/exists-file/blob/master/index.js#L13
If it is not a string an error has to be thrown. Otherwise it is a silent error

**Comment by Kikobeats** [comment]
@zkochan I think that you're right!

**Comment by Kikobeats** [comment]
Open a new issue/pr for existsSymlinks support if you need it 😄

**Comment by zkochan** [comment]
Actually I think it would look nicer in a separate package and then we can cross-reference each-other

**Comment by Kikobeats** [comment]
@zkochan I think the same, so 👍
